hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl setcursor MikuCursor 24")
    hl.exec_cmd("uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("uwsm app -- fcitx5 -d --replace")
    hl.exec_cmd("uwsm app -- sh -c 'cliphist wipe && rm -rf ~/.cache/cliphist && wl-paste --watch cliphist store'")
    hl.exec_cmd("uwsm app -- awww-daemon")
    hl.exec_cmd("uwsm app -- ~/.config/scripts/wall.sh")
    hl.exec_cmd("uwsm app -- gammastep -t 6500:3500 -l 45:25")
    hl.exec_cmd("uwsm app -- nm-applet --indicator")
    hl.exec_cmd("uwsm app -- kdeconnect-indicator")
    hl.exec_cmd("uwsm app -- mpris-scrobbler -vvv")
    hl.exec_cmd("uwsm app -- sh -c 'while ! wpctl status >/dev/null 2>&1; do sleep 0.2; done; wayle panel start'")
    hl.exec_cmd("uwsm app -- ~/.config/scripts/preload_firefox.sh")
    hl.exec_cmd("uwsm app -- nicotine")
    hl.exec_cmd("uwsm app -- ~/.config/scripts/kdenlive-rpc")
end)
