--enable-wayland-ime
--enable-features=UseOzonePlatform,WaylandWindowDecorations,VaapiVideoDecoder
--ozone-platform-hint=wayland
--ozone-hint=auto
--use-gl=angle
--use-angle=vulkan
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--disable-features=UseChromeOSDirectVideoDecoder
